// Generated by Selenium IDE
const { Builder, By, Key, until, Capabilities  } = require('selenium-webdriver')
const assert = require('assert')

//Read .env file
const dotenv = require('dotenv');
dotenv.config();
//Set up envs
const testHost = process.env.PROD_HOST;
const testPort = process.env.PROD_PORT;
const browserHost = process.env.BROWSER_HOST;
const browserPort = process.env.BROWSER_PORT;
//Set up URLs
const browserURL = "http://"+browserHost+":"+browserPort+"/wd/hub";
const testURL = "http://"+testHost+":"+testPort+"/";

describe('kube-me-prebuild', function() {
	this.timeout(30000)
	let driver
	let vars
	beforeEach(async function() {
		console.log("Using Browser : "+browserURL)
		driver = await new Builder()
		.usingServer(browserURL) 
		.forBrowser('firefox')
		.build();
		vars = {};
	})
	afterEach(async function() {
		await driver.quit();
	})
	it('kube-me-stateless-test', async function() {
		console.log("Connecting to " + testURL);
		await driver.get(testURL);
		console.log("Successfully connected " + testURL);
		await ClickComponent(driver,'css',".container > .btn");
		console.log("linkText('STATELESS APPLICATION')).click()");
		await driver.findElement(By.linkText("STATELESS APPLICATION")).click();
		await KeyComponent(driver, 'name', "name", "kube-me");
		await KeyComponent(driver, 'name', "namespace", "tiny-tenant");
		await KeyComponent(driver, 'name', "replicas", "5");
		await KeyComponent(driver, 'name', "image", "asawakow/kube-me:latest");
		await KeyComponent(driver, 'name', "requestCpu", "128m");
		await KeyComponent(driver, 'name', "requestMemory", "256Mi");
		await KeyComponent(driver, 'name', "limitCpu", "256m");
		await KeyComponent(driver, 'name', "limitMemory", "512Mi");
		await KeyComponent(driver, 'name', "envs.0.name", "PORT-NO");
		await KeyComponent(driver, 'name', "envs.0.value", "3000");
		await ClickComponent(driver,'css','.fade:nth-child(1) div:nth-child(22) > .row > .btn');
		await KeyComponent(driver, 'name', "envs.1.name", "IMAGE");
		await KeyComponent(driver, 'name', "envs.1.value", "KUBE-ME");
		await ClickComponent(driver,'css',".row:nth-child(3) > .btn-primary");
		await ClickComponent(driver,'css',".row:nth-child(3) > .col-2 > .btn");
		await ClickComponent(driver,'css',".w-25:nth-child(3) > input");
		await KeyComponent(driver, 'name', "ports.0.name", "http-kubeme");
		await KeyComponent(driver, 'name', "ports.0.number", "3000");
		await ClickComponent(driver,'name',"ports.0.protocol");
		await ClickComponent(driver,'name',"ports.0.expose");
	})
	it('kube-me-stateful-test', async function() {
		console.log("Connecting to " + testURL);
		await driver.get(testURL);
		console.log("Successfully connected " + testURL);
		await ClickComponent(driver,'css',".container > .btn");
		console.log("linkText('STATEFUL APPLICATION')).click()");
		await driver.findElement(By.linkText("STATEFUL APPLICATION")).click();
		await KeyComponent(driver, 'css', ".fade:nth-child(2) .my-1:nth-child(1) > .w-75", "kube-me");
		await KeyComponent(driver, 'css', ".fade:nth-child(2) .my-1:nth-child(3) > .w-75", "tiny-tenant");
		await KeyComponent(driver, 'css', ".fade:nth-child(2) .my-1:nth-child(5) > .w-75", "4");
		await KeyComponent(driver, 'css', ".fade:nth-child(2) .my-1:nth-child(8) > .w-75", "asawakow/kube-me:latest");
		await KeyComponent(driver, 'css', ".fade:nth-child(2) .my-1:nth-child(12) > .w-75", "128m");
		await KeyComponent(driver, 'css', ".fade:nth-child(2) .my-1:nth-child(14) > .w-75", "128Mi");
		await KeyComponent(driver, 'css', ".fade:nth-child(2) .my-1:nth-child(17) > .w-75", "256m");
		await KeyComponent(driver, 'css', ".fade:nth-child(2) .my-1:nth-child(19) > .w-75", "512Mi");
		await KeyComponent(driver, 'css', ".fade:nth-child(2) .col-5:nth-child(1) > .w-75", "stateful");
		await KeyComponent(driver, 'css', ".fade:nth-child(2) .col-5:nth-child(2) > .w-75", "yes");
		await ClickComponent(driver,'css','.fade:nth-child(2) div:nth-child(22) > .row > .btn');
		await KeyComponent(driver, 'name', "envs.1.name", "my-env");
		await KeyComponent(driver, 'name', "envs.1.value", "3000");
		await ClickComponent(driver,'css','div:nth-child(24) > .row > .btn');
		await KeyComponent(driver, 'name', "volumeMounts.1.name", "log");
		await KeyComponent(driver, 'name', "volumeMounts.1.mountPath", "/var/log");
		await KeyComponent(driver, 'name', "volumeMounts.1.storageClassName", "nimble-default-class");
		await KeyComponent(driver, 'name', "volumeMounts.1.size", "5Gi");
		await KeyComponent(driver, 'css', "div:nth-child(27) .w-100", "http-web");
		await KeyComponent(driver, 'css', "div:nth-child(27) .col:nth-child(2) > .row:nth-child(2)", "3000");
	})
})
async function ClickComponent(driver, by, name, isLog=true) {
	if (isLog) console.log("Clicking component "+by+" : "+name);
	if (by == 'name') await driver.findElement(By.name(name)).click();
	else if (by == 'css') await driver.findElement(By.css(name)).click();
	else if (by == 'linkText') await driver.findElement(By.linkText(name)).click();
}
async function KeyComponent(driver, by, name, key, isLog=true) {
	const debugMsg = "Component "+by+" "+name+"'s value: ";
	let resultMsg = "";
	let element;
	if (isLog) console.log("Keying component "+by+" : "+name);
	//Set ELement
	if (by == 'name')  element = driver.findElement(By.name(name));
	else if (by == 'css') element =  driver.findElement(By.css(name));
	//Clear and SendKeys
	await element.clear();
	await element.sendKeys(key); 
	if (isLog) {
		resultMsg = await element.getAttribute("value");
		console.log(debugMsg+resultMsg);
	}
}
function sleep(ms) {
	return new Promise((resolve) => {
	  setTimeout(resolve, ms);
	});
  }   
