apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-me
  labels:
    app: kube-me
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-me
  template:
    metadata:
      labels:
        app: kube-me
    spec:
      containers:
        - name: kube-me
          image: asawakow/kube-me
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 256Mi
          ports:
            - name: http-web
              containerPort: 80
              protocol: TCP

