apiVersion: v1
kind: Service
metadata:
  name: kube-me-dev
  labels:
    app: kube-me-dev
spec:
  type: NodePort
  selector:
    app: kube-me-dev
  ports:
    - name: http-kube-me-ci
      nodePort: 30555
      protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kube-me-ci-ingress
spec:
  rules:
  - host: kube-me-ci.ezmeral.hpe.lab
    http:
      paths:
      - path: /
        backend:
          serviceName: kube-me
          servicePort: 3000
