apiVersion: v1
kind: Service
metadata:
  name: kube-me-dev
  labels:
    app: kube-me-dev
spec:
  type: NodePort
  selector:
    app: kube-me-dev
  ports:
    - name: http-dev-kube-me
      nodePort: 30555
      protocol: TCP
      port: 3000
      targetPort: 3000

