apiVersion: v1
kind: Service
metadata:
  name: kube-me
  labels:
    app: kube-me
spec:
  type: NodePort
  selector:
    app: kube-me
  ports:
    - name: http-web
      protocol: TCP
      port: 80
      targetPort: 80

