apiVersion: v1
kind: Service
metadata:
  name: svc-my-app
  namespace: my-ns
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: www-http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
    - name: www-https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30008
